name = "grab-a-cup"
compatibility_date = "2026-09-08"
pages_build_output_dir = "."

[vars]
ECPAY_MODE = "stage"


[[d1_databases]]
binding = "DB"
database_name = "grabacup-db"
database_id = "760d7eb0-5f58-4880-9749-14f54c8df99a"
